export const SHOW_CREATE_NEW_GAME = "SHOW_CREATE_NEW_GAME";
export const SHOW_CREATE_NEW_ACHIEVEMENT = "SHOW_CREATE_NEW_ACHIEVEMENT";
export const SHOW_CREATE_NEW_ACHIEVEMENT_CARD =
  "SHOW_CREATE_NEW_ACHIEVEMENT_CARD";
export const SHOW_CREATE_BULK_ACHIEVEMENTS = "SHOW_CREATE_BULK_ACHIEVEMENTS";
export const SHOW_ACHIEVEMENT_DELETE_SELECTION =
  "SHOW_ACHIEVEMENT_DELETE_SELECTION";

export const FORCE_REFRESH_GAMES = "FORCE_REFRESH_GAMES";
export const FORCE_REFRESH_ACHIEVEMENT = "FORCE_REFRESH_ACHIEVEMENT";

export const ADD_ACHIEVEMENT_DELETE = "ADD_ACHIEVEMENT_DELETE";
export const REMOVE_ACHIEVEMENT_DELETE = "REMOVE_ACHIEVEMENT_DELETE";
